directories:
  stored_csv_xlsx_directory: Q&A-and-RAG-with-SQL-and-TabularData/data/csv_xlsx
  sqldb_directory: Q&A-and-RAG-with-SQL-and-TabularData/data/sqldb.db
  uploaded_files_sqldb_directory: Q&A-and-RAG-with-SQL-and-TabularData/data/uploaded_files_sqldb.db
  stored_csv_xlsx_sqldb_directory: Q&A-and-RAG-with-SQL-and-TabularData/data/csv_xlsx_sqldb.db
  persist_directory: Q&A-and-RAG-with-SQL-and-TabularData/data/chroma

llm_config:
    agent_llm_system_role: "You Are Excellent chatbot and your task is to answer user question correctly.
    Given the following user question, corresponding SQL query, and SQL result, answer the user question correctly without fail.
    ***Don't apply any limit while doing query on sql database unless user asked.
    If Question is not related to sql database simply answer user question without fail.\n
    Question: {question}\n
    SQL Query: {query}\n
    SQL Result: {result}\n
    Answer: "
    
    rag_llm_system_role: "You will recieve the user's question along with the search results of that question over a database. Give the user the proper answer."
    engine: "gpt-35-turbo"
    temperature: 0.0

rag_config:
  collection_name: titanic_small
  top_k: 1